package deployment

import "encoding/json"

// swagger:ignore
type EndpointSpec struct {
	ID              string          `json:"id"`
	Group           string          `json:"group"`
	Name            string          `json:"name"`
	Method          string          `json:"method"`
	Path            string          `json:"path"`
	Summary         string          `json:"summary"`
	RequestType     string          `json:"request_type,omitempty"`
	ResponseType    string          `json:"response_type,omitempty"`
	Body            json.RawMessage `json:"body"`
	ResponseExample json.RawMessage `json:"response_example,omitempty"`
}

func EndpointSpecs() []EndpointSpec {
	return []EndpointSpec{
		{
			ID:              "health",
			Group:           "Core",
			Name:            "Health",
			Method:          "GET",
			Path:            "/api/v1/health",
			Summary:         "Service liveness",
			ResponseType:    "HealthResult",
			Body:            nil,
			ResponseExample: rawExample(map[string]string{"status": "ok"}),
		},
		{
			ID:           "proxy-nginx",
			Group:        "Proxy",
			Name:         "Install nginx",
			Method:       "POST",
			Path:         "/api/v1/proxy/nginx/install",
			Summary:      "Remote web proxy installer",
			RequestType:  "ProxyInstallRequest",
			ResponseType: "ProxyInstallResult",
			Body: rawExample(ProxyInstallRequest{
				SSH:             exampleSSHOptions("proxy.example.internal"),
				LocalConfigPath: "",
			}),
			ResponseExample: rawExample(ProxyInstallResult{
				Host:        "proxy.example.internal",
				Name:        "nginx",
				PackageName: "nginx",
				BinaryName:  "nginx",
				ServiceName: "nginx",
				ConfigPath:  "/etc/nginx/nginx.conf",
			}),
		},
		{
			ID:           "proxy-haproxy",
			Group:        "Proxy",
			Name:         "Install HAProxy",
			Method:       "POST",
			Path:         "/api/v1/proxy/haproxy/install",
			Summary:      "Remote web proxy installer",
			RequestType:  "ProxyInstallRequest",
			ResponseType: "ProxyInstallResult",
			Body: rawExample(ProxyInstallRequest{
				SSH:             exampleSSHOptions("proxy.example.internal"),
				LocalConfigPath: "",
			}),
			ResponseExample: rawExample(ProxyInstallResult{
				Host:        "proxy.example.internal",
				Name:        "haproxy",
				PackageName: "haproxy",
				BinaryName:  "haproxy",
				ServiceName: "haproxy",
				ConfigPath:  "/etc/haproxy/haproxy.cfg",
			}),
		},
		{
			ID:           "garage-node",
			Group:        "Storage",
			Name:         "Garage node",
			Method:       "POST",
			Path:         "/api/v1/storage/s3/garage/node",
			Summary:      "Deploy a Garage S3 storage node",
			RequestType:  "GarageNodeRequest",
			ResponseType: "GarageNodeResult",
			Body: rawExample(GarageNodeRequest{
				SSH:               exampleSSHOptions("garage.example.internal"),
				Version:           "v2.2.0",
				BinaryPath:        "/usr/local/bin/garage",
				ConfigPath:        "/etc/garage.toml",
				MetadataDir:       "/var/lib/garage/meta",
				DataDir:           "/var/lib/garage/data",
				DBEngine:          "sqlite",
				ReplicationFactor: 1,
				RPCBindAddr:       "[::]:3901",
				RPCPublicAddr:     "",
				RPCSecret:         "",
				S3APIBindAddr:     "[::]:3900",
				S3Region:          "garage",
				S3RootDomain:      ".s3.local",
				S3WebBindAddr:     "[::]:3902",
				S3WebRootDomain:   ".web.local",
				S3WebIndex:        "index.html",
				K2VAPIBindAddr:    "[::]:3904",
				AdminAPIBindAddr:  "[::]:3903",
				AdminToken:        "",
				MetricsToken:      "",
				LogLevel:          "garage=info",
			}),
			ResponseExample: rawExample(GarageNodeResult{
				Host:          "garage.example.internal",
				BinaryPath:    "/usr/local/bin/garage",
				ConfigPath:    "/etc/garage.toml",
				ServiceName:   "garage",
				RPCPublicAddr: "garage.example.internal:3901",
				S3Endpoint:    "http://garage.example.internal:3900",
				AdminEndpoint: "http://garage.example.internal:3903",
				AdminToken:    "generated-admin-token",
				MetricsToken:  "generated-metrics-token",
			}),
		},
		{
			ID:           "garage-token",
			Group:        "Storage",
			Name:         "Garage S3 token",
			Method:       "POST",
			Path:         "/api/v1/storage/s3/garage/token",
			Summary:      "Create bucket credentials",
			RequestType:  "GarageTokenRequest",
			ResponseType: "GarageTokenResult",
			Body: rawExample(GarageTokenRequest{
				SSH:                exampleSSHOptions("garage.example.internal"),
				BucketName:         "app-assets",
				KeyName:            "app-assets-key",
				CreateBucket:       BoolPtr(true),
				AllowCreateBuckets: BoolPtr(false),
				AllowRead:          BoolPtr(true),
				AllowWrite:         BoolPtr(true),
				AllowOwner:         BoolPtr(true),
				BinaryPath:         "/usr/local/bin/garage",
				ConfigPath:         "/etc/garage.toml",
				S3Endpoint:         "",
				LayoutZone:         "dc1",
				LayoutCapacity:     "100G",
			}),
			ResponseExample: rawExample(GarageTokenResult{
				Host:              "garage.example.internal",
				S3Endpoint:        "http://garage.example.internal:3900",
				BucketName:        "app-assets",
				KeyName:           "app-assets-key",
				AccessKeyID:       "generated-access-key",
				SecretAccessKey:   "generated-secret-key",
				MCAliasSetCommand: "mc alias set garage http://garage.example.internal:3900 generated-access-key generated-secret-key",
			}),
		},
		{
			ID:           "valkey-install",
			Group:        "Database",
			Name:         "Install Valkey",
			Method:       "POST",
			Path:         "/api/v1/database/valkey/install",
			Summary:      "Install and configure Valkey for remote access",
			RequestType:  "ValkeyInstallRequest",
			ResponseType: "ValkeyInstallResult",
			Body: rawExample(ValkeyInstallRequest{
				SSH:      exampleSSHOptions("cache.example.internal"),
				Username: "app",
				Password: "secret",
				Bind:     "0.0.0.0",
				Port:     6379,
				ACLFile:  "",
			}),
			ResponseExample: rawExample(ValkeyInstallResult{
				Host:     "cache.example.internal",
				Port:     6379,
				Username: "app",
				URI:      "redis://app:secret@cache.example.internal:6379",
			}),
		},
		{
			ID:           "mariadb-install",
			Group:        "Database",
			Name:         "Install MariaDB",
			Method:       "POST",
			Path:         "/api/v1/database/mariadb/install",
			Summary:      "Install and configure MariaDB for remote access",
			RequestType:  "MariaDBInstallRequest",
			ResponseType: "MariaDBInstallResult",
			Body: rawExample(MariaDBInstallRequest{
				SSH:          exampleSSHOptions("db.example.internal"),
				DatabaseName: "appdb",
				Username:     "app",
				Password:     "secret",
				Bind:         "0.0.0.0",
				Port:         3306,
			}),
			ResponseExample: rawExample(MariaDBInstallResult{
				Host:         "db.example.internal",
				Port:         3306,
				DatabaseName: "appdb",
				Username:     "app",
				URI:          "mysql://app:secret@db.example.internal:3306/appdb",
			}),
		},
		{
			ID:           "systemd-app-deploy",
			Group:        "Deploy",
			Name:         "Deploy systemd app",
			Method:       "POST",
			Path:         "/api/v1/deploy/systemd-app",
			Summary:      "Deploy an application as a remote systemd service",
			RequestType:  "SystemdAppDeployRequest",
			ResponseType: "SystemdAppDeployResult",
			Body: rawExample(SystemdAppDeployRequest{
				SSH:               exampleSSHOptions("app.example.internal"),
				AppName:           "orders-api",
				EnvVars:           map[string]string{"APP_ENV": "staging", "PORT": "8080"},
				ServiceUser:       "orders-api",
				ServiceUID:        8888,
				DestinationBinary: "orders-api",
				InstallDir:        "/opt/orders-api",
				SystemdDir:        "/etc/systemd/system",
				SourceDir:         ".",
				SourceBin:         "./dist/orders-api",
				SourcePackage:     ".",
			}),
			ResponseExample: rawExample(SystemdAppDeployResult{
				Host:         "app.example.internal",
				AppName:      "orders-api",
				ServiceName:  "orders-api",
				ServiceUser:  "orders-api",
				InstallDir:   "/opt/orders-api",
				BinaryPath:   "/opt/orders-api/orders-api",
				SystemdUnit:  "/etc/systemd/system/orders-api.service",
				SourceBinary: "./dist/orders-api",
			}),
		},
		{
			ID:           "postgres-app",
			Group:        "Database",
			Name:         "Setup PostgreSQL app database",
			Method:       "POST",
			Path:         "/api/v1/database/postgres/app",
			Summary:      "Create or update an application PostgreSQL database and role",
			RequestType:  "PostgresAppSetupRequest",
			ResponseType: "PostgresAppSetupResult",
			Body: rawExample(PostgresAppSetupRequest{
				SSH:                           exampleSSHOptions("db.example.internal"),
				DatabaseName:                  "orders",
				Username:                      "orders_app",
				Password:                      "secret",
				SchemaName:                    "public",
				CreateDB:                      BoolPtr(true),
				DropFirst:                     BoolPtr(false),
				PostgresUser:                  "postgres",
				PostgresHost:                  "db.example.internal",
				PostgresPort:                  5432,
				PostgresConnDB:                "postgres",
				SetupRemotePostgres:           BoolPtr(true),
				RemotePostgresHBACIDR:         "0.0.0.0/0",
				RemotePostgresAuthMethod:      "scram-sha-256",
				RemotePostgresListenAddresses: "*",
			}),
			ResponseExample: rawExample(PostgresAppSetupResult{
				Host:         "db.example.internal",
				DatabaseName: "orders",
				Username:     "orders_app",
				SchemaName:   "public",
				PostgresHost: "db.example.internal",
				PostgresPort: 5432,
				URI:          "postgres://orders_app:secret@db.example.internal:5432/orders?sslmode=disable",
			}),
		},
		{
			ID:           "proxmox-lxc",
			Group:        "Proxmox",
			Name:         "Create LXC",
			Method:       "POST",
			Path:         "/api/v1/proxmox/lxc",
			Summary:      "Create a new Proxmox LXC container",
			RequestType:  "ProxmoxLXCRequest",
			ResponseType: "ProxmoxLXCResult",
			Body: rawExample(ProxmoxLXCRequest{
				Auth: ProxmoxAuthOptions{
					HostURL:  "https://pve01.example.internal:8006",
					APIToken: "root@pam!infractl=secret",
				},
				Node:         "pve01",
				VMID:         9191,
				Hostname:     "orders-staging-01",
				Password:     "secret",
				OSTemplate:   "local:vztmpl/debian-12-standard_12.7-1_amd64.tar.zst",
				Storage:      "local-lvm",
				RootFSSize:   "9",
				Memory:       1024,
				Swap:         512,
				Cores:        1,
				CPUUnits:     1024,
				Net0:         "name=eth0,bridge=vmbr0,ip=dhcp,type=veth",
				Unprivileged: BoolPtr(true),
				Start:        BoolPtr(true),
				Console:      BoolPtr(true),
			}),
			ResponseExample: rawExample(ProxmoxLXCResult{
				Node:     "pve01",
				VMID:     9191,
				Hostname: "orders-staging-01",
				Status:   "created",
				Started:  true,
				Console:  true,
			}),
		},
		{
			ID:           "proxmox-vm-create",
			Group:        "Proxmox",
			Name:         "Create VM",
			Method:       "POST",
			Path:         "/api/v1/proxmox/vm",
			Summary:      "Create a new Proxmox VM from a template",
			RequestType:  "ProxmoxVMCreateRequest",
			ResponseType: "ProxmoxVMCreateResult",
			Body: rawExample(ProxmoxVMCreateRequest{
				Auth: ProxmoxAuthOptions{
					HostURL:  "https://pve01.example.internal:8006",
					APIToken: "root@pam!infractl=secret",
				},
				SSH:          exampleSSHOptions("pve01.example.internal"),
				Node:         "pve01",
				VMID:         9201,
				TemplateVMID: 9000,
				Name:         "orders-staging-01",
				MemoryMB:     2048,
				Sockets:      1,
				Cores:        2,
				Description:  "Orders staging VM",
				Storage:      "local-lvm",
				FullClone:    BoolPtr(true),
				Start:        BoolPtr(true),
				CIUser:       "admin",
				SshPublicKeys: []string{
					"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBexample user@example",
				},
				IPConfig0:         "ip=dhcp",
				CISnippetsStorage: "local",
			}),
			ResponseExample: rawExample(ProxmoxVMCreateResult{
				Node:         "pve01",
				VMID:         9201,
				TemplateVMID: 9000,
				Name:         "orders-staging-01",
				Status:       "created",
				Started:      true,
			}),
		},
		{
			ID:           "proxmox-vm-template",
			Group:        "Proxmox",
			Name:         "Create VM template",
			Method:       "POST",
			Path:         "/api/v1/proxmox/vm/template",
			Summary:      "Create a Proxmox VM template from a cloud image",
			RequestType:  "ProxmoxVMTemplateRequest",
			ResponseType: "ProxmoxVMTemplateResult",
			Body: rawExample(ProxmoxVMTemplateRequest{
				Auth: ProxmoxAuthOptions{
					HostURL:  "https://pve01.example.internal:8006",
					APIToken: "root@pam!infractl=secret",
				},
				SSH:              exampleSSHOptions("pve01.example.internal"),
				Node:             "pve01",
				VMID:             9000,
				Name:             "ubuntu-2404-cloudimg",
				ImageURL:         "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img",
				Storage:          "local-lvm",
				CloudInitStorage: "local-lvm",
				MemoryMB:         2048,
				Sockets:          1,
				Cores:            1,
				Description:      "Ubuntu 24.04 cloud image template",
				Net0:             "virtio,bridge=vmbr0",
				SCSIHW:           "virtio-scsi-pci",
				DiskBus:          "scsi0",
				BootOrder:        "scsi0",
				Agent:            BoolPtr(true),
				SerialConsole:    BoolPtr(true),
				CleanupImage:     BoolPtr(true),
			}),
			ResponseExample: rawExample(ProxmoxVMTemplateResult{
				Node:             "pve01",
				VMID:             9000,
				Name:             "ubuntu-2404-cloudimg",
				ImportedVolumeID: "local-lvm:vm-9000-disk-0",
				Template:         true,
			}),
		},
	}
}

func exampleSSHOptions(host string) SSHOptions {
	return SSHOptions{
		Host:             host,
		User:             "ubuntu",
		PrivateKeyBase64: "base64-encoded-private-key",
		UseAgent:         true,
		Port:             22,
	}
}

func rawExample(value interface{}) json.RawMessage {
	payload, err := json.Marshal(value)
	if err != nil {
		return nil
	}
	return payload
}
